---
title: "Répertoire des données"
title-block-banner: false
description: | 
  Les données utilisées sont disponibles pour téléchargement.
# à changer
date: "`r format(Sys.time(), '%d %B, %Y')`"
# Modifier les détails que vous voulez
author:
  - name: "James Roy"
    # Votre site web perso ou github
    url: https://github.com/JJamesRoy
    # les champs d'affiliation sont optionnels, vous pouvez les
    # comment out en ajoutant un # devant.
    affiliation: FAS1002
    affiliation-url: https://FAS1002.github.io/A22
    # changer pour votre propre orcid id
    # https://orcid.org/ pour vous inscrire.
    orcid: 0000-0002-0941-5961

# TRUE == Générer une citation pour cette page précise. Pour enlever, mettre false.
citation: false
# Inclure les références que vous utilisez dans vos rapports. Je conseille Zotero pour construire
# ce fichier ou de connecter RStudio directement pour pouvoir citer avec @nom-de-reference.
bibliography: references.bib
---

```{r, warning = FALSE, include = FALSE}
library(DT)
library(fs)
```

```{r, message = FALSE, warning = FALSE, include = FALSE}
bulk = path("data", "bulk_data")

if (file.exists(paste0(bulk, ".zip"))){
  file.remove(paste0(bulk, ".zip"))
} else {
  print("Fichier non-existant")
}
# Supprime ancien zip

files2zip <- dir(path("data", "raw"), full.names = TRUE)
zip(zipfile = bulk, files = files2zip)

# Zip les nouveaux fichiers
```

```{r, message = FALSE, warning = FALSE, include = FALSE}
base = path("data","processed")

base_file = path(base, list.files(base))

dat = read.csv(base_file)
```

## Nettoyées

Les données modifiées se trouvent ci-dessous :

```{r, warning = FALSE, echo = FALSE}
datatable(
  dat, extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('csv', 'excel')
  )
)

# Met le bouton download
```

## Brutes

Les données brutes sont disponibles ici dans un fichier compressé.

```{=html}
<a href="/data/bulk_data.zip" download>Télécharger les données</a>
```
## Graphiques

Les graphiques sont disponibles dans ce fichier zip.

```{=html}
<a href="/data/bulk_plot.zip" download>Télécharger les graphiques</a>
```
