---
title: "Présentation du projet"
title-block-banner: true
description: | 
  Description détaillé du projet.
# à changer
date: "`r format(Sys.time(), '%d %B, %Y')`"
# Modifier les détails que vous voulez
author:
  - name: "James Roy"
    # Votre site web perso ou github
    url: https://github.com/JJamesRoy
    # les champs d'affiliation sont optionnels, vous pouvez les
    # comment out en ajoutant un # devant.
    affiliation: FAS1002
    affiliation-url: https://FAS1002.github.io/A22
    # changer pour votre propre orcid id
    # https://orcid.org/ pour vous inscrire.
    orcid: 0000-0002-0941-5961

# TRUE == Générer une citation pour cette page précise. Pour enlever, mettre false.
citation: false
# Inclure les références que vous utilisez dans vos rapports. Je conseille Zotero pour construire
# ce fichier ou de connecter RStudio directement pour pouvoir citer avec @nom-de-reference.
bibliography: references.bib
---

## Description du projet

Dans ce projet, on analysera des données sur le CO2 de @owidco2andothergreenhousegasemissions, sur l'énergie de @owidenergy ainsi que sur l'espérance de vie de @lifeexp. On essaiera de trouver des résultats intéressants, qu'ils soient robustes statistiquement ou non. Il sera aussi possible de regarder des visualisations de données, lesquelles vont mettre en lien certaines variables.

## Résultats trouvés

Bien que plusieurs résultats ont été trouvés, cette partie va en présenter trois.

1.  D'abord, que les pays occidentaux (globalement Europe et Amériques) ont bien réussi à améliorer leur efficacité énergétique (voir graphique p1)
2.  En deuxième, le lien entre PIB par habitant et espérance de vie fort, et ce, dans l'ensemble des continents (voir graphique p4)
3.  En dernier, les événements historiques ont des impacts marqués sur l'espérance de vie d'une région (voir graphique p3)

## Conclusion

En somme, plusieurs résultats intéressants ont été trouvés avec les données disponibles. Il aurait intéressant de pousser l'analyse plus loin et peut-être trouver des relations causales entre l'utilisation de certaines formes d'énergies et l'espérance de vie.

## Suite

Pour la suite, il suffit de se rendre sur cette [page.](import.qmd)
